### ISSUE TITLE
Crear clase DTO y clase ViewModel de Alumno

### ISSUE THREAD

**Issue by saulroc** [Carlosgv13/ProyectoEscuela#4]
Crear carpeta DTOS y meter la clase CrearAlumnoDTO con las propiedades Id y Nombre
Crear carpeta ViewModels y meter la clase CrearAlumnoViewModel con la propiedad Nombre
Modificar el método Crear de la clase AlumnosActions para que reciba como parámetro de entrada un ViewModel como el que hemos creado y devuelva un DTO como el creado
En la clase AlumnosActions crear una propiedad de tipo lista llamada Alumnos

**Comment by Carlosgv13** [comment]
#4
